### ISSUE TITLE
Are there docs showing which Akka APIs are supported in-browser?

### ISSUE THREAD

**Issue by ryanberckmans** [unicredit/akka.js#100]
This is a question, not an issue. Hope that's ok!

Are there docs showing which Akka APIs are supported in-browser?

For example, I'm currently running a TCP server in Akka using `akka.io.{IO, Tcp}`.  I have a sense that a TCP server won't run in-browser since only websocket clients are supported.

But, I am interested to use case classes like `akka.io.Tcp.Received(ByteString)` with akka-js to fake a websocket client connection. This will help my code reuse between in-browser and server-side. Does akka-js support types like `akka.io.Tcp.{case class}`?

**Comment by andreaTP** [comment]
I'm sorry to say that there is no "out-of-the-box"  documentation for what is included and what is not (like in Scala.js itself).
As a general rule of thumb everything IO related is excluded but you can check in a case-by-case basis (e.g.: this empty directory means that it's all excluded when compiling to Scala.Js https://github.com/akka-js/akka.js/tree/master/akka-js-actor/js/src/main/scala/akka/io )

**Comment by andreaTP** [comment]
BTW: this is a demo example of using websockets witj Akka.Js:
https://github.com/andreaTP/scalaX2017/blob/master/client/src/main/scala/TweetSourceActor.scala
