### ISSUE TITLE
Upgrade to Akka 2.6.1

### ISSUE THREAD

**Issue by PerWiklander** [unicredit/akka.js#103]
Upgrading to newer versions of 2.5 looked like more of a maintenance task. Any thoughts on what needs to be done to get up to 2.6 now that it's been out for a while?

My main interest is to use Akka Typed in the browser together with Lagom 1.6 on the server.

**Comment by andreaTP** [comment]
Hey @PerWiklander , thanks for your interest in the project!
I'm pretty swamped lately but I will try to work on upgrading to Akka 2.6 eventually, haven't evaluated yet the effort, but the building blocks are the same and should be pretty doable, just a matter of time.

**Comment by PerWiklander** [comment]
If you get the time to evaluate and provide a todo list here, I can help with the grunt work.

**Comment by an-tex** [comment]
Hi, I‘d be happy to help out too. My main use case is Akka Stream together with Lagom 1.6. Cheers

**Comment by andreaTP** [comment]
you can track the progress on this branch:
https://github.com/akka-js/akka.js/tree/update2.6.1

Actor and Stream(and related modules) are compiling, linking and running the tests.

currently the next two foreseeable steps are:
 - implement a facade for `slf4j` over something Scala.js compatible ( https://github.com/wvlet/airframe/tree/master/airframe-log ) and make the sub-project `akkaJsActorTypedJS` compile
 - check the failing tests in Stream and understand if something fundamental is still missing or are just necessary divergences over Akka on the JVM and fix or exclude(add an empty file with a colliding name in the `src/js` folder) the relevant tests

if anyone wanna pick something please sync over Gitter.

**Comment by PerWiklander** [comment]
The first point looks easy enough, if airframe-log is the preferred lib: https://github.com/wvlet/airframe/tree/master/airframe-log#using-with-slf4j

**Comment by andreaTP** [comment]
@PerWiklander it's actually the other way around, we need to provide the API of `slf4j` basing the implementation on airframe, but you will see as soon as you try to run compile :-)

**Comment by andreaTP** [comment]
Quick update:
Akka Typed is ported and the (few remaining) tests are running.
Still need to get back to Stream tests, but getting closer!

**Comment by andreaTP** [comment]
Looks like it is done!
Now, before publishing the stable release I would love some help to try out the new version in your projects.
For this purpose I published a snapshot version:
`1.2.6.1-RC1-SNAPSHOT`
available only for Scala 2.12 (Scala 2.13 support needs this: https://github.com/wvlet/airframe/issues/868 to be resolved)

You would need to add the snapshot resolver to your build.sbt:
```
resolvers += Resolver.sonatypeRepo("snapshots")
```

**Comment by an-tex** [comment]
onya mate! i'll try go get to get this update into a snapshot of https://github.com/mliarakos/lagom-js/issues/4 to test it.

**Comment by an-tex** [comment]
hey @andreaTP . you sure the snapshot publish to sonatype went through? can't resolve it (resolver added)

**Comment by andreaTP** [comment]
haven't tried to resolve it through sbt but is there: 
https://oss.sonatype.org/content/repositories/snapshots/org/akka-js/akkajsactortyped_sjs0.6_2.12/1.2.6.1-RC1-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/org/akka-js/akkajsactorstream_sjs0.6_2.12/1.2.6.1-RC1-SNAPSHOT/

are you compiling for Scala 2.12 @an-tex ?

**Comment by an-tex** [comment]
omg good old sbt scope screwed me ;) thanks for the quick reply though, got it!

**Comment by an-tex** [comment]
The akka-streams side is looking good!
I've updated lagomjs to use this  snapshot (https://github.com/mliarakos/lagom-js/pull/5) and it's example project (https://github.com/mliarakos/lagom-scalajs-example/pull/1) which is using Akka Stream Source's.

**Comment by andreaTP** [comment]
Thanks a lot for the double check @an-tex !
I will test against all the examples in the Akka documentation and, if good, I will publish the stable soon.

**Comment by PerWiklander** [comment]
Thanks guys! This was the perfect Christmas gift for me :-)

**Comment by andreaTP** [comment]
`1.2.6.1` is out! :-) thanks for the support! :-)

**Comment by an-tex** [comment]
Amazing work @andreaTP !
