### ISSUE TITLE
Maven Central - Scala 2.13 artifacts?

### ISSUE THREAD

**Issue by OndrejSpanel** [unicredit/akka.js#113]
It seems Scala 2.13 is supported: https://github.com/akka-js/akka.js/blob/64188aa5a9e8965af7d7b703ae6a6963eb35a969/build.sbt#L6

Still, I cannot find any 2.13 artifacts on the [Maven Central](https://mvnrepository.com/artifact/org.akka-js/akkajsactor), only 2.12 ones.

**Comment by andreaTP** [comment]
@OndrejSpanel Scala 2.13 is almost supported actually, we need to run the tests and there is some work pending:
https://github.com/akka-js/akka.js/pull/112

This will be the next thing I will tackle.

**Comment by andreaTP** [comment]
Akka.Js 2.2.6.3 is out also for Scala 2.13, sorry for the long delay!
https://oss.sonatype.org/content/repositories/public/org/akka-js/akkajsactor_sjs0.6_2.13/2.2.6.3/
