### ISSUE TITLE
would it make sense akka.js to be decoupled from scala and made a stand alone npm published library?

### ISSUE THREAD

**Issue by vladimir-ivanov** [unicredit/akka.js#126]

**Comment by andreaTP** [comment]
it is indeed already shipped indeed:
https://github.com/akka-js/akka.js_bindings
does this answer?

**Comment by vladimir-ivanov** [comment]
> it is indeed already shipped indeed:
> https://github.com/akka-js/akka.js_bindings
> does this answer?

yes, thank you, will be interesting to play with it in ui apps

**Comment by vladimir-ivanov** [comment]
> it is indeed already shipped indeed:
> https://github.com/akka-js/akka.js_bindings
> does this answer?

seems it can only work in nodejs (server side javascript) or am I mistaken?

**Comment by andreaTP** [comment]
And yes it does work in the browser as well
