### ISSUE TITLE
Synchronousness of Akka.JVM

### ISSUE THREAD

**Issue by yawnt** [unicredit/akka.js#15]
Some parts of Akka.JVM are designed to be run synchronously, but unfortunately we cannot block in JS.

For instance, some points that come to mind
- Initialization of logging
- TestKit

TestKit is the toughest one because it really is 100% blocking. So far I've been able to make it work by using a custom event loop which is able to block, but I wouldn't call it a reliable solution. Ideally the test suite should be refactored to use futures.
I do understand however this is a huge undertaking

@rkuhn @andreaTP @andreaferretti

**Comment by rkuhn** [comment]
Yes, rewriting the test suite would be a huge undertaking, and a risky one as well: the test suite is the only thing that keeps us from falling into the abyss—thus is the nature of writing a concurrency toolkit. How does node.js do this? I hear they have “synchronous” APIs that will just stop executing a certain piece of code when it its I/O and resume it when the bytes are ready.

**Comment by colinrgodsey** [comment]
yea, crazy enough there is 'blocking' available through the use of 'fibers' which is supported in V8, and in various forms in node.js. basically this still enforces strict limitations on concurrent access to the JS VM, but it does allow you to run multiple JS stacks in 'fibers' that basically run on a global lock around the VM, and can release the lock inside a function thats executing something outside of the VM (think Thread.sleep())

EDIT: err forgot to make my suggestion. Could isolate some tests that need blocking support to test only on node.js using the npm fibers lib

**Comment by andreaTP** [comment]
this is referred into separate issues, testkit is reworked and now much more stable, extensions must be fixed but do not cause bugs now
