### ISSUE TITLE
porting http header & URI parsing

### ISSUE THREAD

**Issue by bblfish** [unicredit/akka.js#16]
There are a few constructs in akka http that are quite high level and don't depend on a lot of the streaming stuff such as the Akka.http.model.Uri [which I ported a year ago](https://github.com/bblfish/akka.http.model.Uri) and all of the [header parsing code](https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpHeader.scala). Those I think could already be very useful for everyday scala.js http development.

**Comment by yawnt** [comment]
thanks for the idea!
what do you need this for exactly?
i think it would be best if we could focus on getting a single core of features ready and then start to expand, instead of pulling into a multitude of different directions :smile:

**Comment by bblfish** [comment]
Well my client application needs to fetch a lot of resources all over the web, so I have to write a cache in the browser as well as on the server, which is also fetching resources all over the web. It would be nice to be able to use the work done by others there. I have a feeling the HTTP header parsers are very well designed in akka :-)

 Btw, the URI port in `scala.js` a year ago was very much slower that the `java.net.URI` code which was the fastest, way faster than the node.js URI class. Worth checking if anything has changed since then.

**Comment by andreaTP** [comment]
Let keep this for a far future integration.
Anyhow thanks @bblfish to keep in mind his points!
