### ISSUE TITLE
gitter channel?

### ISSUE THREAD

**Issue by bblfish** [unicredit/akka.js#17]
Do you have a [gitter](gitter.im) channel to discuss things?

**Comment by yawnt** [comment]
not yet, we will probably have a gitter channel in the future, once enough people show interest :)
in the meanwhile, both me and @andreaTP hang out in scala.js' gitter channel, so feel free to ping us there and we'll answer

**Comment by andreaTP** [comment]
going to close this if you @bblfish don't mind...

let wait at least the end of @yawnt intern pleaz ;-)
