### ISSUE TITLE
size of optimised binary

### ISSUE THREAD

**Issue by bblfish** [unicredit/akka.js#20]
I ported my application to use `akka.js` and found an increase of size from `251KB` to `394KB`.
The [original application](https://github.com/read-write-web/rww-scala-js/tree/80ec01235006451d98eb5c34c586628246fec395/) produces the following files with `fullOptJs`

``` bash
-rw-r--r--  1 hjs  staff   1.0M 20 Jun 17:18 rww-scala-js-opt.js
-rw-r--r--  1 hjs  staff   251K 20 Jun 17:18 rww-scala-js-opt.js.gz
```

whereas my [ported application](https://github.com/read-write-web/rww-scala-js/tree/3b9c76ec0dc5c542d554e28af2327a07bdbc863d/) produces this:

``` bash
-rw-r--r--  1 hjs  staff   1.6M 20 Jun 15:24 rww-scala-js-opt.js
-rw-r--r--  1 hjs  staff   394K 20 Jun 15:24 rww-scala-js-opt.js.gz
```

Is this due to the weak typing of actors as `Any => Unit` ?

**Comment by yawnt** [comment]
increase from what? what where you using before? akka is not a lightweight dependency, it brings a bunch of features (and hence of code) with it, size increase should be expected

**Comment by bblfish** [comment]
Of course I expect size increases @yawnt . But since `akka.js` is only at version 0.2 I expect you have not made all the optimisations. Hence my question. 

The libs used currently are 

``` scala
      jsDependencies += "org.webjars" % "react" % "0.12.2" / "react-with-addons.js" commonJSName "React",
      libraryDependencies ++= Seq(
        "org.scala-js" %%% "scalajs-dom" % "0.8.1",
        "com.github.japgolly.scalajs-react" %%% "core" % "0.9.0",
        "com.github.japgolly.scalajs-react" %%% "test" % "0.9.0" % "test",
        "com.github.japgolly.scalajs-react" %%% "extra" % "0.9.0",
        "com.github.japgolly.scalajs-react" %%% "ext-scalaz71" % "0.9.0",
        "com.github.japgolly.scalacss" %%% "core" % "0.2.0",
        "com.github.japgolly.scalacss" %%% "ext-react" % "0.2.0",
        "com.lihaoyi" %%% "scalarx" % "0.2.8",
        "org.webjars" % "font-awesome" % "4.3.0-1" % Provided,
        "org.webjars" % "bootstrap" % "3.3.2" % Provided,
        "org.w3" %%% "banana-plantain" % "0.8.2-SNAPSHOT",
        "org.w3" %%% "banana-io-ntriples" % "0.8.2-SNAPSHOT",
        "org.w3" %%% "banana-n3-js" % "0.8.2-SNAPSHOT",
        "org.w3" %%% "banana-jsonld-js" % "0.8.2-SNAPSHOT",
```

@andreaTP on gitter wrote:

> It is due to the use of JSExport for a lot of components to emulate reflection, this will be fixed in future

Do you agree this may explain the increase?
I am asking as this will help me gauge a little bit how much benefit I need to get from the move to akka. Currently I just got the code working to see if it was useable.

**Comment by yawnt** [comment]
partially yes. For instance, ATM, we need to bundle `testkit` **inside** `akka-actor`. That dependency will go away once reflection (https://github.com/scala-js/scala-js/issues/1744) is ready :D

I'm going to close this, as it's more of something we will have to deal with once we've stopped adding files/features. Feel free to reopen it if the size becomes a problem in your application!
