### ISSUE TITLE
problems relationg to opaque objects in communication with WebWorkers

### ISSUE THREAD

**Issue by bblfish** [unicredit/akka.js#26]
Hi, when you write a communication mechanism that allows WebWorkers to talk to each other, watch out for communication that would require opaque objects to be transferred. I can't use the scalajs-rx-idb library because it uses lihaoi's upickle which transforms everything to a string . See https://github.com/viagraphs/scalajs-rx-idb/issues/3

**Comment by andreaTP** [comment]
thanks, I think we will rely on an external pickling library, I hope at some point someone else will take care of this ;-)

**Comment by andreaTP** [comment]
will be superseded by #30
