### ISSUE TITLE
ask pattern hangs when futures >= 2

### ISSUE THREAD

**Issue by yawnt** [unicredit/akka.js#28]

**Comment by andreaTP** [comment]
we need to provide proper tests on the ManagedEventLoop within our testkit implementation.

**Comment by andreaTP** [comment]
this doesn't apply asshown here:
https://github.com/unicredit/akka.js/blob/testkit-rework/akka-js-testkit/js/src/test/scala/akka/testkit/ManagedEventLoopSpec.scala

the problem was probably with wrong initialization phase of ManagedEventLoop
