### ISSUE TITLE
default configuration

### ISSUE THREAD

**Issue by andreaTP** [unicredit/akka.js#42]
find a way to provide a default meaningful configuration that let user use ActorSystem("name") without providing the custom one.

**Comment by colinrgodsey** [comment]
ultimately there needs to be some replacement for the classpath based reference.conf loading... no clue how that would work. scala-js doesnt really have any notion of that, or 'scanning' for available classes/resources etc.

there could maybe be an SBT plugin that just code-gens scala files for any reference.confs seen in the classpath at compile time. Those gen'd classes could JSExport themselves under a special namespace ( ___akkajs.references.124e-153-ae-some-uuid-etc.scala_ ). Could be used for the core packages, as well as anyone else publishing akkajs versions of libs. 

Could then crawl the 'com' object namespace to find the 'reference' configs on a new ActorSystem

**Comment by andreaTP** [comment]
wow an Sbt plugin is totally an opportunity if everything else fail! Good catch!

I was thinking at making a bundle of a reference configuration directly inside akka.js binaries ...

In Scala.Js one can choose to load a configuration from an Ajax call and I really hope to easly let users plug their preferred way.

Just thinking... we could use the mentioned sbt plugin internally to do the job ...

**Comment by andreaTP** [comment]
Embraced a basic macro time loading of "application.conf"
https://github.com/unicredit/shocon/commit/a424481720775c779e685db0a230d81c502d1043

This solution has got a number of disadvantages but at least now there is no need to provide a default configuration every time.

**Comment by andreaTP** [comment]
as far as there is no need of a more advanced configuration loading mechanism I close this that will be eventually be opened in shocon itself later on.
