### ISSUE TITLE
Fix Mailboxes implementation

### ISSUE THREAD

**Issue by andreaTP** [unicredit/akka.js#44]
We must follow Akka ones where presents and do not diverge from the original signatures as highlighted in #43

**Comment by andreaTP** [comment]
It happens that probably `Mailbox.scala` can be totally ported to akka.js working a little bit on utils.
Better check actual implementation of `Mailboxes.scala` that probably diverge too much...

**Comment by andreaTP** [comment]
Aligned back mostly `Mailbox.scala` and `Mailboxes.scala` here: https://github.com/akka-js/akka.js/tree/mailbox-fix

The actual problem is that in Scala.Js is not feasable to implement the "requirement" system, due to reflection lack, although now mailbox is at least configurable and things like `Stashing` are working.

**Comment by andreaTP** [comment]
ok, the fix is available in `1.2.5.2` I close here

**Comment by michaelahlers** [comment]
Been fighting with `Stash` configuration support all day and only now discovered this ticket. :wink: Thanks for the 1.2.5.2 release, @andreaTP!

**Comment by andreaTP** [comment]
Sorry for the caused trouble! Hope you are enjoying it now! It took a while but now we have it! :-)

**Comment by michaelahlers** [comment]
@andreaTP, it's OT, but your work here is _amazing_! Total gamechanger for client-server app. development.

**Comment by andreaTP** [comment]
:-) thanks! still a couple of bits missing to be a game changer but it's promising but let's keep this kind of conversation on gitter: https://gitter.im/akkajs/Lobby :-)
