### ISSUE TITLE
Cross compilation of Tests

### ISSUE THREAD

**Issue by andreaTP** [unicredit/akka.js#48]
Thanks to @solomono we get a great number of tests that already work.
Unfortunately they diverge from akka original sources and this force us to manually realign things.
This is bad an not affordable in the slices of time where akka.js is developed.

At the moment I'm going to evict every failure test but I need a better solution for the future.

**Comment by andreaTP** [comment]
Ok the plan is to start with testkit itself.
The subproject should be restructured to use `assembleAkka` and should be tested properly itself.
Most of the sources should cross-compile.

We still have a blocking in this: https://github.com/unicredit/shocon/issues/5

**Comment by andreaTP** [comment]
After talking with @bvenners it should be worth to rely on their implementation of "Queue for EventLoop" the enabling method that access within tests is `Future.value`.
This will require a bit of understanding of the topic.

**Comment by solomono** [comment]
I presume you have identified test failures that may be resolved by rewriting with futures. Can you please provide further detail concerning where I may gain more understanding of the topic?

**Comment by andreaTP** [comment]
I'm still blocked by configuration issue, I started to cross-compile tests, but I need too to dig the topic better....

**Comment by andreaTP** [comment]
Akka-Testkit is now much more solid on 0.2.4.14-SNAPSHOT, we can go on from there.

**Comment by andreaTP** [comment]
still far from perfect but the testing infrastructure is running more than 800 tests right now on CI I'll close this.
