### ISSUE TITLE
port typesafe.config

### ISSUE THREAD

**Issue by yawnt** [unicredit/akka.js#5]
typesafe.config.Config is written in Java, aka no cross compile..  gotta figure out what to do

@andreaTP @andreaferretti

**Comment by mfirry** [comment]
My two cents: Typesafe Config uses [HOCON](https://github.com/typesafehub/config#using-hocon-the-json-superset), a JSON Supserset. 
We could force using JSON which will be valid HOCON and javascript-_y_ by definition.

**Comment by andreaTP** [comment]
https://github.com/primexx/hocon-config

https://github.com/mingqi/hoconfig-js
