### ISSUE TITLE
Fix extensions implementation

### ISSUE THREAD

**Issue by andreaTP** [unicredit/akka.js#51]
Right now we do not have a check of uniqueness of extensions.
This could be done with a `WeakMap[ActorSystem, HashMap[ExtensionName, ExtensionInstance]]`

just TBD

**Comment by solomono** [comment]
Can you please explain. I  Extensions are believe unique within a ActorSystems. Is the objective to have them unique across all ActorSystems within an process.

**Comment by andreaTP** [comment]
Yes currently they are hacky... everytime an Extension is required there is an overload of ExtensionKey that simply instantiate a new element. So they are not guaranteed to be unique.
i.e. https://github.com/unicredit/akka.js/blob/master/akka-js-actor/js/src/main/scala/akka/event/ExtensionKey.scala

We need to instantiate a global object (a WeakMap) to guarantee uniqueness.

**Comment by andreaTP** [comment]
Extension registration in Akka 2.5 is now compatible and I should not hack a solution.
Next update will solve this.

**Comment by andreaTP** [comment]
New release is fixed
