### ISSUE TITLE
Akka Typed integration

### ISSUE THREAD

**Issue by andreaTP** [unicredit/akka.js#52]
this should be easy, it needs the implementation of some methods within our `akka.util.Unsafe`, probably a little bit of copy paste should do the trick ;-)
The build is already configured within the branch `typed`

**Comment by solomono** [comment]
Do I assume if I attempt to build the typed branch the issue will be immediately obvious.

**Comment by andreaTP** [comment]
now the branch compiles, and link properly, but doesn't work... I'm on this so please chat on gitter if you need updates on this.

**Comment by tannerezell** [comment]
+1 Would love to see akka typed support on the JS side.

**Comment by andreaTP** [comment]
ok, this is starting to work here:
https://github.com/akka-js/akka.js/tree/retyped
still missing Logging, testing and configuration most notably.

But a basic example compile and run :-) https://github.com/andreaTP/akkajs-typed-baby-steps

**Comment by andreaTP** [comment]
Default logging (i.e. not configurable so far ...) integrated, default configuration applied, testing infrastructure ported.
Only notable missing is that JUnit tests are not running so far, but a few ScalaTests are and are properly passing.

**Comment by andreaTP** [comment]
Travis integration aligned, if CI become green I guess I can publish at least a SNAPSHOT release of `typed`

**Comment by andreaTP** [comment]
addressed in #80

**Comment by andreaTP** [comment]
Closing and released in SNAPSHOT, we will benefit from a couple of PR in Akka upstream from definitive release.
