### ISSUE TITLE
Non-Existent Method scala.concurrent.impl.Promise$CompletionLatch.releaseShared

### ISSUE THREAD

**Issue by darkfrog26** [unicredit/akka.js#56]
When I try to run my Scala.js tests (that work with Akka on the JVM) I'm getting the following at fast opt:

```
[error] Referring to non-existent method scala.concurrent.impl.Promise$CompletionLatch.releaseShared(scala.Int)scala.Boolean
[error]   called from scala.concurrent.impl.Promise$CompletionLatch.apply(scala.util.Try)scala.Unit
[error]   called from scala.concurrent.impl.Promise$CompletionLatch.apply(java.lang.Object)java.lang.Object
[error]   called from scala.Function1.apply$mcVD$sp(scala.Double)scala.Unit
[error]   called from scala.collection.AbstractSeq.apply$mcVD$sp(scala.Double)scala.Unit
```

Is there something I'm doing wrong or is this a missing feature?

**Comment by andreaTP** [comment]
Hi Matt, thanks for reporting! Right we are not done with Akka Testkit but things are getting better, I published 0.2.4.14-SNAPSHOT of akka-testkit for akka.js, and we can start from here. Anyhow, can you detail your configuration and attach a code snippet to look into please?

**Comment by darkfrog26** [comment]
Unfortunately I haven't had the time to narrow down the exact problem, but here's the relevant code:

```
import akka.actor.{ActorSystem, Cancellable, Scheduler}

import scala.concurrent.{Awaitable, CanAwait, Promise, TimeoutException}
import scala.concurrent.duration._
import scala.concurrent.ExecutionContext.Implicits.global

trait Transition {
  def finished: Boolean
  def init(): Unit
  def invoke(delta: Double): Unit

  def start(interval: FiniteDuration = 16.milliseconds): TransitionInstance = {
    var instance: Option[TransitionInstance] = None
    var lastTime = System.currentTimeMillis()
    init()
    val cancellable = Transition.scheduler.schedule(0.seconds, interval) {
      if (!finished) {
        val time = System.currentTimeMillis()
        val delta = (time - lastTime) / 1000.0
        invoke(delta)
        lastTime = time
      } else {
        instance.foreach(_.finish())
      }
    }
    instance = Some(new TransitionInstance(cancellable))
    instance.get
  }

  def andThen(next: Transition): Sequence = new Sequence(List(this, next))
  def and(other: Transition): Parallel = new Parallel(Set(this, other))
}

class TransitionInstance(cancellable: Cancellable) extends Awaitable[Boolean] {
  private val promise = Promise[Boolean]
  private val future = promise.future
  private var _finished: Boolean = false
  private var _cancelled: Boolean = false

  def finished: Boolean = _finished
  def cancelled: Boolean = _cancelled

  private[transition] def finish(): Unit = {
    cancellable.cancel()
    _finished = true
    promise.success(true)
  }

  def cancel(): Unit = if (_finished) {
    cancellable.cancel()
    _finished = true
    _cancelled = true
    promise.success(false)
  }

  @scala.throws[InterruptedException](classOf[InterruptedException])
  @scala.throws[TimeoutException](classOf[TimeoutException])
  override def ready(atMost: Duration)(implicit permit: CanAwait): TransitionInstance.this.type = {
    future.ready(atMost)(permit)
    this
  }

  @scala.throws[Exception](classOf[Exception])
  override def result(atMost: Duration)(implicit permit: CanAwait): Boolean = future.result(atMost)(permit)
}

object Transition {
  val system: ActorSystem = ActorSystem("transitions")
  val scheduler: Scheduler = system.scheduler

  def dispose(): Unit = {
    system.terminate()
  }
}
```

**Comment by andreaTP** [comment]
OK, please give a try to the 0.2.4.14-SNAPSHOT of testkit and import Awaitable and CanAwait from akka.testkit instead the stdlib once. And please report the result

**Comment by darkfrog26** [comment]
Perhaps I'm doing something wrong, but I'm unable to resolve the dependency properly.  Although I think it might be because the akkajsactor wasn't published properly (https://oss.sonatype.org/content/repositories/snapshots/eu/unicredit/akkajsactor_sjs0.6_2.12/ is empty).

When I add:

`libraryDependencies += "eu.unicredit" %%% "akkajstestkit" % "0.2.4.14-SNAPSHOT"`

I get:

`unresolved dependency: eu.unicredit#akkajsactor_sjs0.6_2.12;0.2.4.14-SNAPSHOT: not found`

**Comment by andreaTP** [comment]
Sorry @darkfrog26  my fault, now is fixed!

**Comment by darkfrog26** [comment]
Made the switch, got it to finally compile but having some really buggy problems, and I think I'm going to write my own light-weight facade to abstract JS / JVM scheduling of tasks (which is what I was trying to solve with akkajs).  I'll check back on this project when it's a little more stable but you can go ahead close this ticket if you like.

Thanks for your effort.

**Comment by andreaTP** [comment]
Scheduling works consistently in Akka.Js since a lot of time, teskit is intended only for use in test environment and has got a lot of limitations at least on JS.VM.

To have consistency you need to write everything async and compose...

Anyhow thanks for reporting the bug, I'll close this.
