### ISSUE TITLE
TCP/UDP/Networking support in Akka JS through ScalaJS.io

### ISSUE THREAD

**Issue by ghost** [unicredit/akka.js#63]
Has the project considered support networking features through Node with https://github.com/scalajs-io/scalajs.io?

**Comment by andreaTP** [comment]
Hi @mhsjlw what are you looking for exactly?
I'm working on remote but I think in a different direction, Akka is a framework for managing concurrency and building applications, so, it is a bit orthogonal to what scalajs-io provide, at least at a brief view...

**Comment by ghost** [comment]
Akka has I/O options for networking. It would be interesting to be able to run your Akka server on both Node and Scala through akka-js and scalajs-io

**Comment by andreaTP** [comment]
It is already possible to run Akka servers on Node ... using Scala.Js capabilities, probably I'm missing what kind of integration are you talking about, could you provide a concrete example?

**Comment by ghost** [comment]
Sure (this is an example). I run a very popular TCP echo service. I have some design constraints that prevent me from launching Scala servers at the moment. I need to run my current Akka code which uses TCP internet sockets as a server which accept TCP clients. Currently, Akka I/O isn't supported, I purposed using Scala.IO to implement the I/O portion of the Akka library so I can run my existing code

**Comment by andreaTP** [comment]
right now you can already do it using for example socket from Javascript ...
for example here: https://github.com/andreaTP/beescala/blob/master/server/src/main/scala/WSServerActor.scala
I use a popular Node WebServer to handle WebSockets, unfortunately this is Node specific platform and as for now Akka.Js is JS VM agnostic.
I will really like to keep it like this and have optional/external modules to have specific integrations with different backends.

as said I'm already working on remote you can check the actual status in the relevant branch, but there is still a bit of work to do here.
