### ISSUE TITLE
Documentation on altering basic config

### ISSUE THREAD

**Issue by LogicalTime** [unicredit/akka.js#64]
Documentation or examples should show how to use the basic config with a single value override. Like set the loglevel to WARN. Would be nice to see that in documentation. The examples only show parsing a full config from a string.
ConfigFactory.load() doesn't work.

**Comment by andreaTP** [comment]
Thanks a lot for your comment, this is indeed a request on ```shocon``` features https://github.com/unicredit/shocon

Anyhow, yes I agree it will be useful to show an example usage of ```withFallback``` outside this codebase.

```ConfigFactory.load()``` actually work with some caveats (probably not properly documented though).

With shocon ```ConfigFactory.load()``` load files at *compile time* and they should be on the classpath before macro-time so a sbt tweak is needed as you can see from here: https://github.com/unicredit/shocon/blob/master/build.sbt#L32

**Comment by andreaTP** [comment]
Realized that it was tricky enough, added an helper in sources and brief explanation in Readme.MD:
https://github.com/akka-js/akka.js#add-ons

Everything is shipped with 0.2.4.17

Thanks a lot for rising the question! @LogicalTime
