### ISSUE TITLE
compilation fails by using akka-js together with scala-java-time

### ISSUE THREAD

**Issue by AlexanderRay** [unicredit/akka.js#68]
Hi,

I have scala-js compile issues by using  of [scala-java-time](https://github.com/cquiroz/scala-java-time) library together with akka-js. It seems as a duplicate of [Non-Existant method SimpleDateFormat (#62)](https://github.com/akka-js/akka.js/issues/62) issue.

Here is a test project to reproduce it [akkajs-date-issue](https://github.com/AlexanderRay/akkajs-date-issue). 

**temporary workaround** would be to add [SimpleDateFormat.scala](https://github.com/AlexanderRay/akkajs-date-issue/blob/master/src/main/scala/SimpleDateFormat.scala) to your codebase.

**Comment by andreaTP** [comment]
Agreed a solution and integrated `scala-java-locales` in akka.js.
For testing purposes you can start using `0.2.5.0-RC2-SNAPSHOT` published for scala 2.11 and 2.12 on Sonatype Snapshots

**Comment by andreaTP** [comment]
solved in `1.2.5.0`
