### ISSUE TITLE
Make Scala-JS 1.0 ready

### ISSUE THREAD

**Issue by ghost** [unicredit/akka.js#73]
Any ETA, anything one could help with?

**Comment by andreaTP** [comment]
Hi @Unmoving , I have started working on this, the main constrain right now is that shocon should be compiled for 1.0.0 and it depends on fastparse.
Porting one of the transitive dependencies of fastparse itself will help a lot.

**Comment by andreaTP** [comment]
Akka.Js is cross-published for Scala.Js 1.X since version `2.2.6.3` and solely for it since `2.2.6.4`
