### ISSUE TITLE
Fastparse binary compatibility issue. Conflict with scalapb.

### ISSUE THREAD

**Issue by LogicalTime** [unicredit/akka.js#77]
I get linking errors when using scalapb and akkajs. They are on fastparse 0.4.2 and you are on 0.4.4 now. 
fastparse.all$.CharsWhile() is removed between 0.4.2 and 0.4.4.
Fastparse documentation says it's not binary compatible. Perhaps we should all them to release a binary compatible 1.0.x. Parboiled2 is released for Scalajs I believe (check out scala-uri's dependencies).

**Comment by andreaTP** [comment]
Thanks for the report! Actually fast parse is a transitive dependency front shocon. I'm not really sure how to target this issue... Downgrading and releasing shocon with fast parse 0.4.2 looks really a temporary workaround... 🙁 cross releasing doesn't sound as an option... Any idea?

**Comment by andreaTP** [comment]
BTW did you give a try explicitly excluding fast parse from Akka. Js import?

**Comment by andreaTP** [comment]
I have just checked in one of my projects and I do not find problems in scalapb + akka.js could you provide a minimal repro please? So that I can check what is happening more in depth.

**Comment by LogicalTime** [comment]
Yes, I'll get on that tomorrow if I can. I asked fastparse's author to see if he is up for going to a major release that is binary compatible. Did you do scalapb's Scalajs dependency and go for fastparse 0.4.4?

**Comment by andreaTP** [comment]
aaa, sorry, I have understood the other way around,
ok updating `shocon` to 0.4.4 is totally feasible!

Feel free to take the chance to make a PR, or I will do it before `1.2.5.5` release.

I leave this open until `shocon` is updated. 

Thanks for the report.

**Comment by andreaTP** [comment]
actually, PR sent:
https://github.com/unicredit/shocon/pull/25

**Comment by LogicalTime** [comment]
Just thought I'd mention that fastparse released 1.0 0 which is identical to 0.4.4 and should be binary compatible going forwards. So this issue is closed as soon as you update to a shocon version that uses fastparse 0.4.4 or 1.0.0.

**Comment by andreaTP** [comment]
ok, I make the PR on `shocon` and try to integrate it when 2.5.7 is out.

**Comment by andreaTP** [comment]
here you have:
https://github.com/unicredit/shocon/pull/27

**Comment by andreaTP** [comment]
A little late but Akka.Js 1.2.5.8 is out and should solve this, please try it out and feel free to reopen in case.
