### ISSUE TITLE
Usage along with Ajax calls

### ISSUE THREAD

**Issue by kelebra** [unicredit/akka.js#78]
Hi,

I recently started a project using akka.js (which is a fantastic library). However I ran into a small issue with creation of actor that tries to _send Ajax request_:

```scala

type Dispatcher[T] = String => Future[T]

  class HttpAccessActor[T](dispatcher: Dispatcher[T]) extends Actor with ActorLogging {

    def receive: Receive = {
      case request: Request =>
        pipe(
          Ajax.get(request.build)
            .map(_.responseText)
            .flatMap(dispatcher)
            .andThen { case info => println(info) }
        ) to sender()
    }
  }
```

And whenever I send message to this actor test runs out of timeout even though operation succeeded:

```bash
- should make simple http call *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (30 seconds) during expectMsgClass waiting for class scala.util.Try
[info]   at org.scalatest.WordSpecLike.invokeWithFixture$1(/Users/kelebra/Documents/IdeaProjects/tkachuko-blog/target/scala-2.12/tkachuko-blog-test-fastopt.js:121380:15)
[info]   ...
Success(Response(104.189.124.210))
```

Is it issue in interoperability of `akka.js` and `scalajs-dom` or some issue with `pipe` pattern?

Please find below all version information:

```scala
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.20")
scalaVersion := "2.12.2"
sbtVersion := "0.13.16"

"org.scala-js" %%% "scalajs-dom" % "0.9.2",
"org.akka-js" %%% "akkajsactor" % "1.2.5.4"
```

Thanks a lot beforehand.

**Comment by kelebra** [comment]
Please ignore the issue. Scala.js changed its `npm` dependency and i did not notice that. Sorry for disturbance.

**Comment by andreaTP** [comment]
:+1:

**Comment by andreaTP** [comment]
I think this is a problem with Scala.js. Dom itself, give it a try straight in a main. BTW you normally do not have to explicitly pass the dispatcher around, you have it from context.dispatcher

**Comment by andreaTP** [comment]
wait wait, finally in front of a pc I read your complete post.
The problem here is that `TestKit` is limited in the sense that you cannot test anything that does any kind of IO or operations with external bindings (such as an Http request ...)

This is due to the "blocking" API that comes with `akka-testkit`.

this is briefly mentioned in the Readme:
https://github.com/akka-js/akka.js#caveats

but yes I agree that a more accurate note makes totally sense here.

If you really what to make a test on these calls I suggest you to avoid `akka-testkit` and use plain `scalatest`

**Comment by kelebra** [comment]
Thanks a lot for closer look and suggestion, sir! I decoupled http access layer from the actor (which turned out to be good design decision as well 👍 ) and now test looks like this:

```scala
abstract class ActorSpec(_system: => ActorSystem) extends TestKit(_system)
  with WordSpecLike with Matchers with BeforeAndAfterAll with ImplicitSender with DefaultTimeout {

  final override def afterAll: Unit = shutdown()
}

class HttpAccessActorTest extends ActorSpec(ActorSystem("HttpAccessActorTest")) {

  case class Response(ip: String)
  implicit val decoder: Decoder[Response] = deriveDecoder[Response]

  val mock: HttpAccess = HttpAccess.static("{\"ip\": \"2602:306:8bd7:cd20:ac87:afb5:21e1:8dc8\"}")

  "Http actor" should {

    "make http call and deserialize json" in {

      system.actorOf(HttpAccessActor(mock)) ! Request("http", "ip.jsontest.com")

      val response = expectMsgClass(classOf[Try[Response]])
      response.get.ip should not be empty
    }
  }
}
```

which results with this issue:

```bash
[error] scala.scalajs.js.JavaScriptException: TypeError: Cannot read property 'system$1' of null
```

I remember previously there were some issues with timeouts in tests but not sure if this is still the case nowadays. By the way, your help is much appreciated.

**Comment by andreaTP** [comment]
I tried to narrow it down to a self contained example:
```scala
import akka.actor._
import akka.testkit._
import org.scalatest._
import scala.util.{Try, Success}

abstract class ActorSpec(_system: => ActorSystem) extends TestKit(_system)
  with WordSpecLike with Matchers with BeforeAndAfterAll with ImplicitSender with DefaultTimeout {

  final override def afterAll: Unit = shutdown()
}

class HttpAccessActorTest extends ActorSpec(ActorSystem("HttpAccessActorTest")) {

  case class Response(ip: String)
  case class Request(protocol: String, url: String)

  "Http actor" should {

    "make http call and deserialize json" in {

      system.actorOf(Props(new Actor{
        def receive = {
          case req: Request =>
            sender() ! Success(Response("127.0.0.1"))
        }
      })) ! Request("http", "ip.jsontest.com")

      val response = expectMsgClass(classOf[Try[Response]])
      response.get.ip should not be empty
    }
  }
}
```
and this works for me versions are:
Scala -> 2.12.2 / 2.11.11 (tested on both)
Akka.JS -> 1.2.5.4
Node -> v7.10.1 / v8.4.0 (tested on both)

Could you please share you latest implementation of `HttpAccessActor` ?

Thanks!

**Comment by kelebra** [comment]
Thanks for a simplified test. It also works fine for me. I reproduced the issue mentioned previously on this minimal example:

```scala
import akka.actor._
import com.tkachuko.blog.common.ActorSpec

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.Future

abstract class ActorSpec(_system: => ActorSystem) extends TestKit(_system)
  with WordSpecLike with Matchers with BeforeAndAfterAll with ImplicitSender with DefaultTimeout {

  final override def afterAll: Unit = shutdown()
}

class OtherTest extends ActorSpec(ActorSystem("HttpAccessActorTest")) {

  case class Response(ip: String)

  case class Request(protocol: String, url: String)

  "Http actor" should {

    "make http call and deserialize json" in {

      system.actorOf(Props(new Actor {

        import akka.pattern.pipe

        def receive = {
          case _: Request => pipe(Future.successful(Response("127.0.0.1"))) to sender()
        }
      })) ! Request("http", "ip.jsontest.com")

      val response = expectMsgClass(classOf[Response])
      response.ip should not be empty
    }
  }
}
```

Output:
```bash
[info] OtherTest:
[info] Http actor
...
[error] scala.scalajs.js.JavaScriptException: TypeError: Cannot read property 'system$1' of null
...
```

My working assumption is that the issue lies in usage of __`Future`__ and __`pipe() to`__. My implementation of `HttpAccessActor` also used `pipe` and `Future`s:

```scala
type Unmarshal[T] = String => Future[T]

sealed trait HttpAccess {

  def apply(request: Request): Future[String]
}

  class HttpAccessActor[T](httpAccess: HttpAccess,
                           unmarshal: Unmarshal[T]) extends Actor with ActorLogging {

    def receive: Receive = {
      case request: Request =>
        pipe(
          httpAccess(request)
            .flatMap(unmarshal)
            .andThen { case reply => log.info("{} => {}", request, reply) }
        ) to sender()
    }
  }
```

However previous piece of code looks definitely like a __minimal verifiable example__ to me  so we probably should concentrate on that.

Thanks a lot for your attention and assistance on this issue.

**Comment by andreaTP** [comment]
Thanks a lot to you for reporting @kelebra ! Users experiences are incredibly useful for improving projects! :-)

Actually I wasn't able to reproduce and get your error message (to it fails with a timeout...).
But I spotted something there :-) I agree that wasn't easy to find for an end user :-( and the problem is indeed in:
```scala
import scala.concurrent.ExecutionContext.Implicits.global
```
basically importing it you give the default `ExecutionContsxt` available as implicit to the [pipe](https://doc.akka.io/api/akka/current/akka/pattern/index.html#pipe[T](future:scala.concurrent.Future[T])(implicitexecutionContext:scala.concurrent.ExecutionContext):PipeToSupport.this.PipeableFuture[T]) method.
But for running blocking tasks with `Testkit` the `ExecutionContext` is different and is not compatible with the default one.

For resolving the issue you can remove the import and instead:
```scala
import system.dispatcher
```
within the `Spec` scope or (even better)
```scala
import context.dispatcher
```
within the actor implementation scope.

e.g.:
```scala
import context.dispatcher
pipe(Future.successful(Response("127.0.0.1"))) to sender()
```

I really need to document this better ...
B.T.W. the usage of different `ExecutionContext`s is anyhow harmful even with Scala on JVM if it is accidental (IDEs are failing I think in giving you suggestions on this side ...)

Please tell me if this solves your problem.

**Comment by kelebra** [comment]
Thanks a lot. Issue is solved as per your suggestion and works like a charm 👍

**Comment by andreaTP** [comment]
thank you! I make a note on this next time I go through the Readme!
(this remember me that I should definitely write some decent documentation ... )

**Comment by kelebra** [comment]
Let me know if you need any help on that, would be glad to contribute :beers:
