### ISSUE TITLE
Creating an ActorSystem is very slow in Firefox

### ISSUE THREAD

**Issue by nightkr** [unicredit/akka.js#82]
Repro repo: https://github.com/teozkr/repro-akka-js-slow-startup

On my laptop, creating an ActorSystem in Firefox Nightly (61) takes around 3450ms. Chrome 62 takes 655ms to create the same ActorSystem on the same laptop.

Chrome profile: https://raw.githubusercontent.com/teozkr/repro-akka-js-slow-startup/master/profile-chrome.json
Firefox profile: https://perfht.ml/2J0XWUa

From what I can tell, the main culprit is parsing the default HOCON config files, but I'm far from an expert on FastParse performance.

**Comment by nightkr** [comment]
For the record, these numbers are from fastOptJS, but fullOptJS follows the same pattern (~400ms for Chrome, ~1000ms for Firefox).

**Comment by andreaTP** [comment]
This is extremely interesting, actually I used to profile Akka.js on Node... This week I'm still in vacation but next week I will give this a closer look! Thanks a lot for opening the issue!

**Comment by andreaTP** [comment]
I started looking at this, and it looks like a "bug" or "problem" in Firefox itself (probably on caching).

In a firefox `incognito window` I have constantly performances close to chrome, both fast and full opt code, could you confirm @teozkr ?

**Comment by andreaTP** [comment]
Ok, I re-read your issue and I cannot reproduce such a huge difference, on my machine performance of Firefox 59.0.1 is in the worst case double than Chrome 65.0.
Still always better in private mode in FF.

**Comment by tarsa** [comment]
I had to edit index.html to add "repro-" prefix to generated JS file and it then ran fine.

Chrome 65 loads in about 370ms on first load (without console opened) and 420 ms on subsequent loads (with opened console).
Firefox 59 loads in about 480ms on first load (without console opened). Subsequent loads take usually 490ms, but sometimes spike to about 600ms.

It doesn't matter much whether I run tests in normal mode or private/incognito mode. I have few extensions in Chrome and none in Firefox.

Overall, average load time in Chrome (420ms) is not hugely better than in Firefox (490ms) on my PC.

My OS is Ubuntu 16.04.4 LTS 64-bit.

**Comment by andreaTP** [comment]
@tarsa thanks for sharing your results! I have similar configuration and similar results (just slightly better on Chrome and a little better on Firefox in private mode)

**Comment by nightkr** [comment]
That's even weirder. On the same Firefox build fastOptJS now takes ~1270ms to load, incognito and otherwise.

Chrome is hovering around 600ms in both cases as well.

**Comment by andreaTP** [comment]
ok, I got this a spin and the problem is actually the slowness of parsing.

changing your code to:
```scala
    val config: Config =
      akkajs.Config.default

    val before = System.currentTimeMillis()
    ActorSystem("repro-as", config)
    val after = System.currentTimeMillis()
    val delta = after - before
    println(s"After ActorSystem, took $delta ms")
```

shows clearly that the parsing of the configuration takes (on my machine) > 3 times the time to spin the ActorSystem up (350 ms config, 80 ms ActorSystem in Chrome).

I have a few ideas on how to overcome this in most of common cases but it will be an issue on `shocon` library.

**Comment by nightkr** [comment]
Yeah, that's what I got from the profiler too. As a crappy workaround, I wonder if it would be viable to move the parsing to a macro...

**Comment by andreaTP** [comment]
it's possible, but it has a number of caveats, I'm on it @teozkr ;-) (help is always appreciated)

**Comment by andreaTP** [comment]
update:
https://github.com/akka-js/shocon/tree/macroTime +
https://github.com/akka-js/akka.js/tree/startupPerf 

almost half the startup time of the ActorSystem, I will try to publish a Snapshot version to let you test.
It's still a rough WIP but I'm finally able to find further bottlenecks with the flamecharts.

**Comment by andreaTP** [comment]
shocon is published as: `0.3.0-SNAPSHOT`
Akka.js (only actor for scala 2.11. and 2.12) : `1.2.5.12-SNAPSHOT`

On my machine in Chrome startup time is around 200 ms with fastOpt and ~180 ms in fullOpt.
I will like to hear back from you @teozkr and maybe @tarsa before merging.

I think this is the maximum I can obtain now without re-engineering most of `shocon` basing it on mutable data structures.
cc. @evacchi

**Comment by nightkr** [comment]
That sounds great! I'll have a look at it when I can tomorrow.

**Comment by nightkr** [comment]
Wow.. that cut my time (on fastOptJS and the latest Fx nightly) from 1.3s to 0.3s. That's great. Is there a tip jar anywhere?

**Comment by andreaTP** [comment]
> Is there a tip jar anywhere?
WDYM?

**Comment by nightkr** [comment]
@andreaTP PayPal/Patreon/etc

**Comment by andreaTP** [comment]
I'll like to receive PRs. documentation, other projects ( https://github.com/akka-js ) updates whatever :-) thanks a lot for asking!

**Comment by andreaTP** [comment]
@teozkr just an head up:
with a more principled approach in the macro: https://github.com/akka-js/shocon/blob/macroTime/shared/src/main/scala/eu/unicredit/shocon/ConfigMacroLoader.scala#L23

in Chrome now startup time is around 50 ms :-)

**Comment by nightkr** [comment]
That link is a 404 for me. :/

**Comment by andreaTP** [comment]
updated: https://github.com/akka-js/shocon/blob/master/shared/src/main/scala/org/akkajs/shocon/ConfigMacroLoader.scala#L23

**Comment by andreaTP** [comment]
`1.2.5.13` is out now :-)
