### ISSUE TITLE
Upgrade to Akka Stream 2.5.18

### ISSUE THREAD

**Issue by pishen** [unicredit/akka.js#92]
Akka Stream 2.5.18 provides the `zipLatest` function on `Source` and `Flow`, which is useful in frontend development when we have to listen to two event sources simultaneously.

**Comment by andreaTP** [comment]
You are right, I should get back to this, the main issue is the testing infrastructure for Akka Typed that radically changed in 2.5.17, should be doable, but it will require a little.

**Comment by andreaTP** [comment]
just to mention, akka-stream from this branch https://github.com/akka-js/akka.js/tree/updateTo2.5.19 already works, I would need to work more on the typed testkit, stilll ...

**Comment by andreaTP** [comment]
Ci is green with 2.5.19, I will be able to publish early next week. (Found some time to work on this during Scala exchange :-) )
