### ISSUE TITLE
Scala Native support

### ISSUE THREAD

**Issue by francisdb** [unicredit/akka.js#94]
Since scala-native is similar to scala-js and currently also works with a single thread this should not be to hard?
Have you thought about also incorporating akka-http?

Any thoughts?

**Comment by andreaTP** [comment]
Porting Akka to Scala Native is for sure possible and most of the major road-blockers are already gone, at the moment I don't have bandwidth to work on it, still I'm available to support with ideas and my previous experience whoever wanna start an attempt.

Akka-http would be possible, but I do not see major advantages in working on it.

**Comment by francisdb** [comment]
Would you mind sharing how you would tackle this? I might be willing to put some time into it but have no clear idea on how to best start this.

**Comment by andreaTP** [comment]
sure, we move this chat to the gitter channel as it is going to be an interactive process.

**Comment by andreaTP** [comment]
I close this since no more updates.

**Comment by francisdb** [comment]
looking at this scala native is dying...

https://github.com/scala-native/scala-native/graphs/code-frequency

**Comment by andreaTP** [comment]
At best of my knowledge @sjrd took over the development.
A bright future might be ahead instead!
