### ISSUE TITLE
Upgrade to Akka 2.5.25

### ISSUE THREAD

**Issue by ryanberckmans** [unicredit/akka.js#99]
The latest stable release of Akka is 2.5.25.

I am just starting to use akka-js, it looks really cool!  Is there a practice of always upgrading to latest stable release of Akka, or how does that work?

**Comment by andreaTP** [comment]
Hi @ryanberckmans , sorry for the delay, really swamped lately!
The process of upgrading is easy:
 - bump the git tag here: https://github.com/akka-js/akka.js/blob/master/build.sbt#L2
 - fix the compilation errors in all subprojects
 - fix the linking error by running all of the test suites

any help is really appreciated and I can offer guidance over Gitter if you wanna get involved!

**Comment by andreaTP** [comment]
Akka.Js `1.2.5.26` is published to Sonatype :-)
